"""
Auto-generated test cases for: sample_code.py
Generated by: AI Test Platform
Date: 2026-03-24 14:55:35
Coverage target: functions, classes, edge cases

本文件由 AI 测试平台自动生成，包含以下测试类别：
- 正常路径测试 (Normal Path)
- 边界值测试 (Boundary Values)
- 边缘情况测试 (Edge Cases)
- 异常处理测试 (Exception Handling)
"""

import pytest

# 导入被测模块
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'source'))
from sample_code import calculate_discount, fizzbuzz, safe_divide, ShoppingCart

# ============================================================
# Tests for: calculate_discount
# Complexity: 3 | Params: 2 | Raises: ValueError
# ============================================================

class TestCalculateDiscount:
    """Test cases for calculate_discount."""

    @pytest.mark.parametrize("price, discount_rate, expected", [
        (100.0, 0.2, 80.0),
        (200.0, 0.5, 100.0),
        (0.0, 0.0, 0.0),
    ])
    def test_calculate_discount_parametrized(self, price, discount_rate, expected):
        """测试 calculate_discount 多组正常输入（参数化）。"""
        result = calculate_discount(price=price, discount_rate=discount_rate)
        assert result == expected

    def test_calculate_discount_price_boundary(self):
        """测试 calculate_discount 参数 price 的边界值。"""
        try:
            result = calculate_discount(price=0.0, discount_rate=1.0)
            # 如果不抛异常，验证结果合理性
            assert result is not None or result == 0 or result == "" or result == [] or result == {}
        except (ValueError, TypeError, ZeroDivisionError) as e:
            # 边界值可能触发异常，这是可接受的
            assert str(e)  # 确保异常信息不为空

    def test_calculate_discount_discount_rate_boundary(self):
        """测试 calculate_discount 参数 discount_rate 的边界值。"""
        try:
            result = calculate_discount(price=1.0, discount_rate=0.0)
            # 如果不抛异常，验证结果合理性
            assert result is not None or result == 0 or result == "" or result == [] or result == {}
        except (ValueError, TypeError, ZeroDivisionError) as e:
            # 边界值可能触发异常，这是可接受的
            assert str(e)  # 确保异常信息不为空

    def test_calculate_discount_price_none(self):
        """测试 calculate_discount 参数 price 为 None 的情况。"""
        with pytest.raises((TypeError, ValueError, AttributeError)):
            calculate_discount(price=None, discount_rate=1.0)

    def test_calculate_discount_price_wrong_type(self):
        """测试 calculate_discount 参数 price 类型不匹配的情况。"""
        with pytest.raises((TypeError, ValueError, AttributeError)):
            calculate_discount(price="not_a_float", discount_rate=1.0)

    def test_calculate_discount_raises_valueerror(self):
        """测试 calculate_discount: 当 price < 0 时应抛出 ValueError。"""
        with pytest.raises(ValueError, match=r"Price cannot be negative"):
            calculate_discount(price=-1, discount_rate=1.0)

    def test_calculate_discount_raises_valueerror_2(self):
        """测试 calculate_discount: 当 not 0 <= discount_rate <= 1 时应抛出 ValueError。"""
        with pytest.raises(ValueError, match=r"Discount rate must be between 0 and 1"):
            calculate_discount(price=1.0, discount_rate=2)

# ============================================================
# Tests for: fizzbuzz
# Complexity: 4 | Params: 1 | Raises: None
# ============================================================

class TestFizzbuzz:
    """Test cases for fizzbuzz."""

    @pytest.mark.parametrize("n, expected", [
        (1, '1'),
        (3, 'Fizz'),
        (5, 'Buzz'),
        (15, 'FizzBuzz'),
        (7, '7'),
    ])
    def test_fizzbuzz_parametrized(self, n, expected):
        """测试 fizzbuzz 多组正常输入（参数化）。"""
        result = fizzbuzz(n=n)
        assert result == expected

    def test_fizzbuzz_n_boundary(self):
        """测试 fizzbuzz 参数 n 的边界值。"""
        try:
            result = fizzbuzz(n=0)
            # 如果不抛异常，验证结果合理性
            assert result is not None or result == 0 or result == "" or result == [] or result == {}
        except (ValueError, TypeError, ZeroDivisionError) as e:
            # 边界值可能触发异常，这是可接受的
            assert str(e)  # 确保异常信息不为空

    def test_fizzbuzz_n_none(self):
        """测试 fizzbuzz 参数 n 为 None 的情况。"""
        with pytest.raises((TypeError, ValueError, AttributeError)):
            fizzbuzz(n=None)

    def test_fizzbuzz_n_wrong_type(self):
        """测试 fizzbuzz 参数 n 类型不匹配的情况。"""
        with pytest.raises((TypeError, ValueError, AttributeError)):
            fizzbuzz(n="not_a_number")

# ============================================================
# Tests for: safe_divide
# Complexity: 2 | Params: 2 | Raises: ZeroDivisionError
# ============================================================

class TestSafeDivide:
    """Test cases for safe_divide."""

    def test_safe_divide_case1(self):
        """测试 safe_divide 正常输入。"""
        result = safe_divide(a=100.0, b=0.2)
        assert result == 500.0

    def test_safe_divide_case2(self):
        """测试 safe_divide 正常输入。"""
        result = safe_divide(a=200.0, b=0.5)
        assert result == 400.0

    def test_safe_divide_a_boundary(self):
        """测试 safe_divide 参数 a 的边界值。"""
        try:
            result = safe_divide(a=0.0, b=1.0)
            # 如果不抛异常，验证结果合理性
            assert result is not None or result == 0 or result == "" or result == [] or result == {}
        except (ValueError, TypeError, ZeroDivisionError) as e:
            # 边界值可能触发异常，这是可接受的
            assert str(e)  # 确保异常信息不为空

    def test_safe_divide_b_boundary(self):
        """测试 safe_divide 参数 b 的边界值。"""
        try:
            result = safe_divide(a=1.0, b=0.0)
            # 如果不抛异常，验证结果合理性
            assert result is not None or result == 0 or result == "" or result == [] or result == {}
        except (ValueError, TypeError, ZeroDivisionError) as e:
            # 边界值可能触发异常，这是可接受的
            assert str(e)  # 确保异常信息不为空

    def test_safe_divide_a_none(self):
        """测试 safe_divide 参数 a 为 None 的情况。"""
        with pytest.raises((TypeError, ValueError, AttributeError)):
            safe_divide(a=None, b=1.0)

    def test_safe_divide_a_wrong_type(self):
        """测试 safe_divide 参数 a 类型不匹配的情况。"""
        with pytest.raises((TypeError, ValueError, AttributeError)):
            safe_divide(a="not_a_float", b=1.0)

    def test_safe_divide_raises_zerodivisionerror(self):
        """测试 safe_divide: 当 b == 0 时应抛出 ZeroDivisionError。"""
        with pytest.raises(ZeroDivisionError, match=r"Cannot divide by zero"):
            safe_divide(a=1.0, b=0)

# ============================================================
# Tests for class: ShoppingCart
# Base classes: None
# Methods: 5
# ============================================================

class TestShoppingCart:
    """Test cases for ShoppingCart."""

    @pytest.fixture
    def instance(self):
        """创建 ShoppingCart 的测试实例。"""
        return ShoppingCart(owner="hello")

    def test_init(self):
        """测试 ShoppingCart 的构造函数及初始状态。"""
        obj = ShoppingCart(owner="hello")
        assert obj is not None  # TODO: 替换为精确断言（如 assert x == expected_value）
        assert obj.owner == "hello"

    def test_init_defaults(self):
        """测试 ShoppingCart 构造函数的默认参数。"""
        obj = ShoppingCart(owner="hello")
        assert obj is not None

    def test_add_item(self, instance):
        """测试方法 add_item 及其对对象状态的影响。"""
        instance.add_item(name="hello", price=1.0, quantity=1)
        # 验证方法执行后的对象状态变化
        # 可通过 instance.total() 验证状态变化

    def test_add_item_raises_valueerror_1(self, instance):
        """测试方法 add_item: 当 price < 0 时应抛出 ValueError。"""
        with pytest.raises(ValueError, match=r"Price cannot be negative"):
            instance.add_item(name="hello", price=-1, quantity=1)

    def test_add_item_raises_valueerror_2(self, instance):
        """测试方法 add_item: 当 quantity < 1 时应抛出 ValueError。"""
        with pytest.raises(ValueError, match=r"Quantity must be at least 1"):
            instance.add_item(name="hello", price=1.0, quantity=0)

    def test_total(self, instance):
        """测试方法 total 及其对对象状态的影响。"""
        result = instance.total()
        assert result is not None

    def test_item_count(self, instance):
        """测试方法 item_count 及其对对象状态的影响。"""
        result = instance.item_count()
        assert result is not None

    def test_clear(self, instance):
        """测试方法 clear 及其对对象状态的影响。"""
        instance.clear()
        # 验证方法执行后的对象状态变化
        # 可通过 instance.total() 验证状态变化